### PR TITLE
Numerical and Clear/Previous button fixes

### LINKED ISSUE #53: Once I clear an existing answer, the clear button should get disabled

### LINKED ISSUE #64: Bugs in Numerical Answers
- Textarea allows more than one decimal (`.`) to be inserted; leading to NaN
- No limit on number of digits leading to overflow NaN errors
- When number is deleted in text box (backspaces; select all + backspace), it shows zero (`0`) first. Another backspace is required to entirely delete the number

### LINKED ISSUE #66: Submitted answer not restored for Multi-choice
Submitted answer not restored for Multi-choice when previous/next button is clicked. Expected behaviour is to restore previously submitted answers

### PR DESCRIPTION
**Pull request by suryabulusu**
Fixes #53 -- small change in `Footer.vue` 
Fixes #64 , #65  -- Errors in numerical text area
Fixes #66 

## Summary

- Fixed minor bugs
- Removed gray color display for options before quiz submission. Gray color is used only for ungraded questions to indicate the selected answer *post* quiz submission.
- Updated tests accordingly.

## Test Plan

- [x] Test Responsiveness
  - [x] Laptop (1200px)
  - [x] Tablet (760px)
  - [x] Phone (320px)
- [x] Cross-Browser Testing
  - [x] Chrome
  - [x] Firefox
- [ ] ~Local Language Support~
- [x] Hygiene and Housekeeping
  - [x] Self-review
  - [x] Comments have been added appropriately
  - [ ] ~Check for bundle size [here](https://bundlephobia.com/) if adding a package~
  - [ ] ~Added relevant details like Labels/Projects/Milestones etc.~
  - [ ] ~If adding or removing any environment variable, update `docs/ENV.md`, `.env.example` and the Github workflows.~
- [ ] Testing
  - [x] Wrote tests
  - [x] Tested locally
  - [ ] Tested on staging
  - [ ] Tested on an actual physical phone
  - [ ] Tested on production
- [ ] ~Lighthouse Checks~
  - [ ] Images have `alt` attributes
  - [ ] Any `` tags have `width` and `height` specified
  - [ ] Any `target="_blank"` links have `rel="noopener"`
  - [ ] Only SVGs are used as images. If PNGs are used, their size has been optimised.
  - [ ] Any SVG buttons without text have their `aria-label` attributes set

### CODE REVIEW

File: src/types.ts [hunk 1]
```diff
@@ -9,6 +9,7 @@ type questionType =
 type language = "en" | "hi";
 export type quizType = "assessment" | "homework";
 export type quizTitleType = string | null;
+export type textAreaValueType = string | number | null;
```
Comment (suryabulusu) [inline src/types.ts:12]: corrects type error when using `:value` in `<TextArea>`.

File: src/components/Questions/QuestionModal.vue [hunk 2]
```diff
@@ -300,7 +289,7 @@ export default defineComponent({
     const isAnswerSubmitted = computed(() => {
       if (currentQuestionResponseAnswer.value == null) return false
       if (typeof currentQuestionResponseAnswer.value == "number") {
-        return currentQuestionResponseAnswer.value != null
+        return true
```
Comment (suryabulusu) [inline src/components/Questions/QuestionModal.vue:292]: since Line 290 checks for `null`, no point checking again. Just return `true`

**Comment by deepansh96** [comment]
- One small bug I noticed was that even though I was not able to type any float value in the int type numerical question, I was able to paste a float number. Like I just coped 1.1 from somewhere else and was able to paste that. We don't need to take this up now because I doubt most of the people using this work on laptops. However the issue was that when the user submitted, a 1.1 went to the backend and that was written to the DB. I guess this should get solved using validators. So even 1.1 comes from the frontend, backend will trim it maybe, to 1 if the question is integer type and not float type.

- In a float textbox, If i start a number by typing `.`, then all of a sudden NaN comes up. Ideal behaviour should be that if a user types `.34` it means `0.34`

- One more bug. Try out [this](http://localhost:8080/quiz/62b30326cf4fdd904eea618a?userId=214&apiKey=6qOO8UdF1EGxLgzwIbQN) quiz link. Here, I made the first question ungraded and rest all of them are graded. Graded questions should get colored accordingly when the quiz is submitted or a submitted quiz is reloaded. However, ungraded questions should get no coloring, just a gray background telling the user this is the answer they marked. But when in the quiz provided above, if I select an option on the first question (which is ungraded) and click end test, then go back to the first question, I can see the correct answer colored green. When I reload, things work fine and it shows me the answer I selected.

**Review by deepansh96 — CHANGES_REQUESTED** [review]

File: src/components/Questions/Body.vue [hunk 3]
```diff
@@ -319,18 +321,12 @@ export default defineComponent({
...
 
-    function isNumberLarge(x: Number) {
-      const maxValue: number = 1e10
-      return x > maxValue
-    }
-
-    function checkIfNumberExceedsDecimalDigitLimit(x: Number | null) {
-      const maxDecimalPlaces: number = 10 // max length of digits after decimal
-      return String(x).includes(".") && String(x).split(".")[1].length > maxDecimalPlaces - 1
+    function doCharactersExceedLimit(x: Number | null) {
```
Comment (deepansh96) [inline src/components/Questions/Body.vue:328]: this is specific for numerical answers no?
For subject questions, we have another limit that comes from the backend
I think it wouldn't create any confusion if the name of this method reflected that we're checking for limit of a numerical question and not any other question type

Comment (deepansh96) [reply src/components/Questions/Body.vue:328]: Same case with the variable `MAX_LENGTH_CHARACTERS`.
The `characters` word might confuse someone between subjective questions and numerical questions.

File: src/components/Questions/Body.vue [hunk 4]
```diff
@@ -319,18 +321,12 @@ export default defineComponent({
...
+    function doesNumberContainDecimal(x: Number | null) {
       return String(x).includes(".")
     }
 
-    function isNumberLarge(x: Number) {
-      const maxValue: number = 1e10
-      return x > maxValue
-    }
-
-    function checkIfNumberExceedsDecimalDigitLimit(x: Number | null) {
```
Comment (deepansh96) [inline src/components/Questions/Body.vue]: why was this removed?

File: src/components/Questions/QuestionModal.vue [hunk 5]
```diff
@@ -168,7 +169,7 @@ export default defineComponent({
 
         // if the selection option was already in the response
         // remove it from the response (uncheck it); otherwise add it (check it)
-        const currentResponse = JSON.parse(JSON.stringify(state.draftResponses[props.currentQuestionIndex]))
+        const currentResponse = clonedeep(state.draftResponses[props.currentQuestionIndex])
         // JSON parse + stringify clones the array (which may contain any complex object; responses here)
```
Comment (deepansh96) [inline src/components/Questions/QuestionModal.vue:173]: this comment was not updated. Also, ideally, this comment should come on top of the line above, not below

File: src/components/Questions/Body.vue [hunk 6]
```diff
@@ -323,6 +319,20 @@ export default defineComponent({
       state.isImageLoading = true
     }
 
+    function checkIfNumberContainsDecimal(x: Number | null) {
+      return String(x).includes(".")
+    }
+
+    function isNumberLarge(x: Number) {
```
[the remark this answers is not in the document]
Comment (suryabulusu) [reply src/components/Questions/Body.vue]: removed this function, i think its better to rely on character count only.

File: src/components/Questions/QuestionModal.vue [hunk 7]
```diff
@@ -305,10 +313,10 @@ export default defineComponent({
         return false
       }
       if (isQuestionTypeSubjective.value) return currentDraftResponse != ""
-      if (typeof currentDraftResponse == "number") {
+      if (isQuestionTypeNumericalInteger.value || isQuestionTypeNumericalFloat.value) {
```
Comment (deepansh96) [inline src/components/Questions/QuestionModal.vue:316]: Suggestion -- you can also create another computed variable which tells if the question is of numerical type (either numerical-integer or numerical-float). Not necessary though. If you feel it'll make code more readable you can use that

File: src/components/Questions/QuestionModal.vue [hunk 8]
```diff
@@ -305,10 +313,10 @@ export default defineComponent({
...
         return true
       }
-      return currentDraftResponse.length > 0
+      return Object.keys(currentDraftResponse).length > 0
```
Comment (deepansh96) [inline src/components/Questions/QuestionModal.vue:319]: Didnt understand why this was added

File: src/components/Questions/Body.vue [hunk 9]
```diff
@@ -323,6 +319,20 @@ export default defineComponent({
...
+      const maxValue: number = 1e10
+      return x > maxValue
+    }
+
+    function checkIfNumberExceedsDecimalDigitLimit(x: Number | null) {
```
[the remark this answers is not in the document]
Comment (suryabulusu) [reply src/components/Questions/Body.vue]: i've removed this too -- and relying on overall character count. we can later specify in instructions that no more than `10` characters can be entered in the text box.

**Review by deepansh96 — CHANGES_REQUESTED** [review]

File: src/components/Questions/Body.vue (hunk 3 above)
Comment (suryabulusu) [reply src/components/Questions/Body.vue:328]: shall i name it doNumericalCharacters instead? and `MAX_LENGTH_NUMERICAL_CHARACTERS`

File: src/components/Questions/QuestionModal.vue (hunk 8 above)
Comment (suryabulusu) [reply src/components/Questions/QuestionModal.vue:319]: because `.length` was giving a type error. `curentDraftResponse` need not always be an array or string.

File: src/components/Questions/QuestionModal.vue (hunk 7 above)
Comment (suryabulusu) [reply src/components/Questions/QuestionModal.vue:316]: then we'll get an error that `isQuestionTypeNumericalInteger` is created but not used :P 
i think its better to have two separate computed vals for integer and float, there could be a future case when we may have to use each separately

File: src/components/Questions/Body.vue (hunk 3 above)
Comment (deepansh96) [reply src/components/Questions/Body.vue]: Yes sounds good

File: src/components/Questions/QuestionModal.vue (hunk 8 above)
Comment (deepansh96) [reply src/components/Questions/QuestionModal.vue:319]: I just feel like `Object.keys()` is a bit misleading, even if it works in this case.
Basically we want to check for length because we're assuming that `currentDraftResponse` is an array.
So we should check for that as well.
`Object.keys("abcd").length` also gives a value of 4. I know that when the compiler reaches here, we can be sure that the question is not of subjective type but this line of code is a little misleading.
You can write this 
`Array.isArray(currentDraftResponse) && currentDraftResponse.length > 0`
I tried and it's not giving any error and the code is foolproof. It will always check the length if it's an array.
